server:
  port: 8081



spring:
  application:
    name: products

  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password


  jpa:
    packages-to-scan:
      - iut.nantes.project.products.entity
      - iut.nantes.project.stores.entity

